import graphviz

dot = graphviz.Graph()
dot.attr(rankdir='LR')
dot.node('', shape='none')
dot.node('1')
dot.node('2')
dot.node('3')
dot.node('4')
dot.node('5', shape='doublecircle' )
dot.node('6')
dot.node('7')
dot.node('8', shape='doublecircle' )

dot.edge('','1', dir='forward')
dot.edge('1','2', label='+', dir='forward')
dot.edge('1','2', label='-', dir='forward')
dot.edge('2','3', label='[0-9]', dir='forward')
dot.edge('3','3', label='[0-9]', dir='forward')
dot.edge('3','4', label='.', dir='forward')
dot.edge('4','5', label='[0-9]', dir='forward')
dot.edge('5','5', label='[0-9]', dir='forward')
dot.edge('5','6', label='e', dir='forward')
dot.edge('5','6', label='E', dir='forward')
dot.edge('6','7', label='+', dir='forward')
dot.edge('6','7', label='-', dir='forward')
dot.edge('7','8', label='[0-9]', dir='forward')
dot.edge('8','8', label='[0-9]', dir='forward')

dot.render('grafo', format='pdf')